$.datepicker.regional['es']={
	ckiseText:'Cerrar',
	prevText:'<Ant',
	nextText:'Sig>',
	currentText:'Hoy',
	monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
	dayNames:['Domingo','Lunes','Martes','Miercoles','Jueves','Viernes','Sábado'],
	dayNamesShort:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
	dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
	weekHeader:'Sm',
	firsDay:1,
	isRTL:false,
	showMonthAfterYear:false,
	yearSuffix:''
	};
	$.datepicker.setDefaults($.datepicker.regional['es']);